- hosts: webserver
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
    - name: Iniciar Apache
      service:
        name: apache2
        state: started
    - name: Copiar archivos HTML
      copy:
        src: /ruta/a/tu/proyecto/index.html
        dest: /var/www/html/index.html
